# Time series

## Learning Objectives {-#objectives-time-series}

1. Explain the concept and general properties of stationary, $I(0)$, and integrated, $I(1)$, univariate time series.
2. Explain the concept of a stationary random series.
3. Explain the concept of a filter applied to a stationary random series.
4. Know the notation for backwards shift operator, backwards difference operator, and the concept of roots of the characteristic equation of time series.
5. Explain the concepts and basic properties of autoregressive (_AR_), moving average (_MA_), autoregressive moving average (_ARMA_) and autoregressive integrated moving average (_ARIMA_) time series.
6. Explain the concept and properties of discrete random walks and random walks with normally distributed increments, both with and without drift.
7. Explain the basic concept of a multivariate autoregressive model.
8. Explain the concept of cointegrated time series.

## Theory {#theory-time-series}

**TO ADD THEORY ABOUT TIME SERIES HERE**

## Concept and properties of time series

## Concept of stationary random series

## Concept of a filter applied to a stationary random series

## Notation for operators

## The characteristic equation of time series

## Concept and properties of random walks

## Concept of a multivariate autoregressive model

## Concept of cointegrated time series

## `R` Practice {-#practice-time-series}

**TO ADD R EXAMPLE ABOUT TIME SERIES HERE**
