# Markov processes

```{r 09-markov-processes-01, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Learning Objectives {-#objectives-09}

1. State the essential features of a Markov process model.
2. Define a Poisson process, derive the distribution of the number of events in a given time interval, derive the distribution of inter-event times, and apply these results.
3. Derive the Kolmogorov equations for a Markov process with time independent and time/age dependent transition intensities.
4. Solve the Kolmogorov equations in simple cases.
5. State the Kolmogorov equations for a model where the transition intensities depend not only on age/time, but also on the duration of stay in one or more states.
6. Describe sickness and marriage models in terms of duration dependent Markov processes and describe other simple applications.
7. Demonstrate how Markov jump processes can be used as a tool for modelling and how they can be simulated.

## Theory {-#theory-09}

**TO ADD THEORY ABOUT MARKOV PROCESSES HERE**

## Features of a Markov process model

## Poisson process

## Kolmogorov equations for a Markov process

## Solving Kolmogorv equations

### Simple cases

### More general cases

## Sickness and marriage models

## Markov jump process

### Simulating a Markov jump process

## `R` Practice {-#practice-09}

**TO ADD R EXAMPLE ABOUT MARKOV PROCESSES HERE**